//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.30 at 10:49:32 AM CEST
//

package it.cineca.util.dc.terms;

import it.cineca.util.dc.SimpleLiteral;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * This is included as a convenience for schema authors who need to define a root or container element for all of the DC elements and
 * element refinements.
 * <p>
 * Java class for elementOrRefinementContainer complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementOrRefinementContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://purl.org/dc/terms/}elementsAndRefinementsGroup"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementOrRefinementContainer", propOrder = { "any" })
public class ElementOrRefinementContainer {

	/** The any. */
	@XmlElementRef(name = "any", namespace = "http://purl.org/dc/", type = JAXBElement.class)
	protected List<JAXBElement<SimpleLiteral>> any;

	/**
	 * Gets the value of the any property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the any property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAny().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * 
	 * @return the any {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >} {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
	 */
	public List<JAXBElement<SimpleLiteral>> getAny() {
		if (any == null) {
			any = new ArrayList<JAXBElement<SimpleLiteral>>();
		}
		return any;
	}

}
