//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.11 at 12:29:59 PM CEST
//

package it.cineca.util.oai_dc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * it.cineca.sia.siari.service.mapping.bind.oai_dc package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/** The Constant _Rights_QNAME. */
	private static final QName _Rights_QNAME = new QName("http://purl.org/dc/elements/1.1/", "rights");

	/** The Constant _Relation_QNAME. */
	private static final QName _Relation_QNAME = new QName("http://purl.org/dc/elements/1.1/", "relation");

	/** The Constant _Format_QNAME. */
	private static final QName _Format_QNAME = new QName("http://purl.org/dc/elements/1.1/", "format");

	/** The Constant _Date_QNAME. */
	private static final QName _Date_QNAME = new QName("http://purl.org/dc/elements/1.1/", "date");

	/** The Constant _Type_QNAME. */
	private static final QName _Type_QNAME = new QName("http://purl.org/dc/elements/1.1/", "type");

	/** The Constant _Creator_QNAME. */
	private static final QName _Creator_QNAME = new QName("http://purl.org/dc/elements/1.1/", "creator");

	/** The Constant _Publisher_QNAME. */
	private static final QName _Publisher_QNAME = new QName("http://purl.org/dc/elements/1.1/", "publisher");

	/** The Constant _Subject_QNAME. */
	private static final QName _Subject_QNAME = new QName("http://purl.org/dc/elements/1.1/", "subject");

	/** The Constant _Dc_QNAME. */
	private static final QName _Dc_QNAME = new QName("http://www.openarchives.org/OAI/2.0/oai_dc/", "dc");

	/** The Constant _Language_QNAME. */
	private static final QName _Language_QNAME = new QName("http://purl.org/dc/elements/1.1/", "language");

	/** The Constant _Identifier_QNAME. */
	private static final QName _Identifier_QNAME = new QName("http://purl.org/dc/elements/1.1/", "identifier");

	/** The Constant _Title_QNAME. */
	private static final QName _Title_QNAME = new QName("http://purl.org/dc/elements/1.1/", "title");

	/** The Constant _Source_QNAME. */
	private static final QName _Source_QNAME = new QName("http://purl.org/dc/elements/1.1/", "source");

	/** The Constant _Coverage_QNAME. */
	private static final QName _Coverage_QNAME = new QName("http://purl.org/dc/elements/1.1/", "coverage");

	/** The Constant _Contributor_QNAME. */
	private static final QName _Contributor_QNAME = new QName("http://purl.org/dc/elements/1.1/", "contributor");

	/** The Constant _Description_QNAME. */
	private static final QName _Description_QNAME = new QName("http://purl.org/dc/elements/1.1/", "description");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * it.cineca.sia.siari.service.mapping.bind.oai_dc
	 */
	public ObjectFactory() {}

	/**
	 * Create an instance of {@link ElementType }.
	 * 
	 * @return the element type
	 */
	public ElementType createElementType() {
		return new ElementType();
	}

	/**
	 * Create an instance of {@link OaiDcType }.
	 * 
	 * @return the oai dc type
	 */
	public OaiDcType createOaiDcType() {
		return new OaiDcType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "rights")
	public JAXBElement<ElementType> createRights(ElementType value) {
		return new JAXBElement<ElementType>(_Rights_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "relation")
	public JAXBElement<ElementType> createRelation(ElementType value) {
		return new JAXBElement<ElementType>(_Relation_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "format")
	public JAXBElement<ElementType> createFormat(ElementType value) {
		return new JAXBElement<ElementType>(_Format_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "date")
	public JAXBElement<ElementType> createDate(ElementType value) {
		return new JAXBElement<ElementType>(_Date_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "type")
	public JAXBElement<ElementType> createType(ElementType value) {
		return new JAXBElement<ElementType>(_Type_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "creator")
	public JAXBElement<ElementType> createCreator(ElementType value) {
		return new JAXBElement<ElementType>(_Creator_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "publisher")
	public JAXBElement<ElementType> createPublisher(ElementType value) {
		return new JAXBElement<ElementType>(_Publisher_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "subject")
	public JAXBElement<ElementType> createSubject(ElementType value) {
		return new JAXBElement<ElementType>(_Subject_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link OaiDcType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< oai dc type>
	 */
	@XmlElementDecl(namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/", name = "dc")
	public JAXBElement<OaiDcType> createDc(OaiDcType value) {
		return new JAXBElement<OaiDcType>(_Dc_QNAME, OaiDcType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "language")
	public JAXBElement<ElementType> createLanguage(ElementType value) {
		return new JAXBElement<ElementType>(_Language_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "identifier")
	public JAXBElement<ElementType> createIdentifier(ElementType value) {
		return new JAXBElement<ElementType>(_Identifier_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "title")
	public JAXBElement<ElementType> createTitle(ElementType value) {
		return new JAXBElement<ElementType>(_Title_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "source")
	public JAXBElement<ElementType> createSource(ElementType value) {
		return new JAXBElement<ElementType>(_Source_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "coverage")
	public JAXBElement<ElementType> createCoverage(ElementType value) {
		return new JAXBElement<ElementType>(_Coverage_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "contributor")
	public JAXBElement<ElementType> createContributor(ElementType value) {
		return new JAXBElement<ElementType>(_Contributor_QNAME, ElementType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< element type>
	 */
	@XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "description")
	public JAXBElement<ElementType> createDescription(ElementType value) {
		return new JAXBElement<ElementType>(_Description_QNAME, ElementType.class, null, value);
	}

}
