//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

package it.cineca.util.dii;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the it.cineca.util.dii
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/** The Constant _Type_QNAME. */
	private static final QName _Type_QNAME = new QName("urn:mpeg:mpeg21:2002:01-DII-NS", "Type");

	/** The Constant _Identifier_QNAME. */
	private static final QName _Identifier_QNAME = new QName("urn:mpeg:mpeg21:2002:01-DII-NS", "Identifier");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cineca.util.dii
	 */
	public ObjectFactory() {}

	/**
	 * Create an instance of {@link RelatedIdentifier }.
	 * 
	 * @return the related identifier
	 */
	public RelatedIdentifier createRelatedIdentifier() {
		return new RelatedIdentifier();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< string>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2002:01-DII-NS", name = "Type")
	public JAXBElement<String> createType(String value) {
		return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< string>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2002:01-DII-NS", name = "Identifier")
	public JAXBElement<String> createIdentifier(String value) {
		return new JAXBElement<String>(_Identifier_QNAME, String.class, null, value);
	}

}
