//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for dateType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dateType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.loc.gov/mods/v3>baseDateType">
 *       &lt;attribute name="keyDate" type="{http://www.loc.gov/mods/v3}yes" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dateType")
@XmlSeeAlso({ DateOtherType.class })
public class DateType extends BaseDateType {

	/** The key date. */
	@XmlAttribute
	protected Yes keyDate;

	/**
	 * Gets the value of the keyDate property.
	 * 
	 * @return possible object is {@link Yes }
	 */
	public Yes getKeyDate() {
		return keyDate;
	}

	/**
	 * Sets the value of the keyDate property.
	 * 
	 * @param value allowed object is {@link Yes }
	 */
	public void setKeyDate(Yes value) {
		keyDate = value;
	}

}
