//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

// TODO: Auto-generated Javadoc
/**
 * 010, 020, 022, 024, 028, 037, 856
 * <p>
 * Java class for identifierType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifierType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attGroup ref="{http://www.loc.gov/mods/v3}language"/>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="invalid" type="{http://www.loc.gov/mods/v3}yes" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifierType", propOrder = { "value" })
public class IdentifierType {

	/** The value. */
	@XmlValue
	protected String value;

	/** The type. */
	@XmlAttribute
	protected String type;

	/** The display label. */
	@XmlAttribute
	protected String displayLabel;

	/** The invalid. */
	@XmlAttribute
	protected Yes invalid;

	/** The language. */
	@XmlAttribute(name = "lang")
	protected String language;

	/** The lang. */
	@XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;

	/** The script. */
	@XmlAttribute
	protected String script;

	/** The transliteration. */
	@XmlAttribute
	protected String transliteration;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setType(String value) {
		type = value;
	}

	/**
	 * Gets the value of the displayLabel property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDisplayLabel() {
		return displayLabel;
	}

	/**
	 * Sets the value of the displayLabel property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDisplayLabel(String value) {
		displayLabel = value;
	}

	/**
	 * Gets the value of the invalid property.
	 * 
	 * @return possible object is {@link Yes }
	 */
	public Yes getInvalid() {
		return invalid;
	}

	/**
	 * Sets the value of the invalid property.
	 * 
	 * @param value allowed object is {@link Yes }
	 */
	public void setInvalid(Yes value) {
		invalid = value;
	}

	/**
	 * Gets the value of the language property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLanguage(String value) {
		language = value;
	}

	/**
	 * Gets the value of the lang property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the value of the lang property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLang(String value) {
		lang = value;
	}

	/**
	 * Gets the value of the script property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getScript() {
		return script;
	}

	/**
	 * Sets the value of the script property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setScript(String value) {
		script = value;
	}

	/**
	 * Gets the value of the transliteration property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTransliteration() {
		return transliteration;
	}

	/**
	 * Sets the value of the transliteration property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTransliteration(String value) {
		transliteration = value;
	}

}
