//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for nameType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="namePart" type="{http://www.loc.gov/mods/v3}namePartType"/>
 *         &lt;element name="displayForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="affiliation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="role" type="{http://www.loc.gov/mods/v3}roleType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.loc.gov/mods/v3}idAuthorityXlinkLanguage"/>
 *       &lt;attribute name="type" type="{http://www.loc.gov/mods/v3}nameTypeAttribute" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nameType", propOrder = { "namePartOrDisplayFormOrAffiliation" })
public class NameType {

	/** The name part or display form or affiliation. */
	@XmlElementRefs({ @XmlElementRef(name = "affiliation", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "namePart", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "description", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "role", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "displayForm", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class) })
	protected List<JAXBElement<?>> namePartOrDisplayFormOrAffiliation;

	/** The name type. */
	@XmlAttribute(name = "type")
	protected NameTypeAttribute nameType;

	/** The id. */
	@XmlAttribute(name = "ID")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;

	/** The authority. */
	@XmlAttribute
	protected String authority;

	/** The type. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String type;

	/** The href. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	@XmlSchemaType(name = "anyURI")
	protected String href;

	/** The role. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String role;

	/** The arcrole. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String arcrole;

	/** The title. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String title;

	/** The show. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String show;

	/** The actuate. */
	@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
	protected String actuate;

	/** The language. */
	@XmlAttribute(name = "lang")
	protected String language;

	/** The lang. */
	@XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;

	/** The script. */
	@XmlAttribute
	protected String script;

	/** The transliteration. */
	@XmlAttribute
	protected String transliteration;

	/**
	 * Gets the value of the namePartOrDisplayFormOrAffiliation property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the namePartOrDisplayFormOrAffiliation
	 * property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNamePartOrDisplayFormOrAffiliation().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link RoleType }{@code >} {@link JAXBElement }
	 * 
	 * @return the name part or display form or affiliation {@code <}{@link String }{@code >} {@link JAXBElement }{@code <}{@link String }
	 * {@code >} {@link JAXBElement }{@code <}{@link NamePartType } {@code >} {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	public List<JAXBElement<?>> getNamePartOrDisplayFormOrAffiliation() {
		if (namePartOrDisplayFormOrAffiliation == null) {
			namePartOrDisplayFormOrAffiliation = new ArrayList<JAXBElement<?>>();
		}
		return namePartOrDisplayFormOrAffiliation;
	}

	/**
	 * Gets the value of the nameType property.
	 * 
	 * @return possible object is {@link NameTypeAttribute }
	 */
	public NameTypeAttribute getNameType() {
		return nameType;
	}

	/**
	 * Sets the value of the nameType property.
	 * 
	 * @param value allowed object is {@link NameTypeAttribute }
	 */
	public void setNameType(NameTypeAttribute value) {
		nameType = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getID() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setID(String value) {
		id = value;
	}

	/**
	 * Gets the value of the authority property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAuthority() {
		return authority;
	}

	/**
	 * Sets the value of the authority property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAuthority(String value) {
		authority = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getType() {
		if (type == null) {
			return "simple";
		}
		else {
			return type;
		}
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setType(String value) {
		type = value;
	}

	/**
	 * Gets the value of the href property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getHref() {
		return href;
	}

	/**
	 * Sets the value of the href property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setHref(String value) {
		href = value;
	}

	/**
	 * Gets the value of the role property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRole() {
		return role;
	}

	/**
	 * Sets the value of the role property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRole(String value) {
		role = value;
	}

	/**
	 * Gets the value of the arcrole property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getArcrole() {
		return arcrole;
	}

	/**
	 * Sets the value of the arcrole property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setArcrole(String value) {
		arcrole = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTitle(String value) {
		title = value;
	}

	/**
	 * Gets the value of the show property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getShow() {
		return show;
	}

	/**
	 * Sets the value of the show property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setShow(String value) {
		show = value;
	}

	/**
	 * Gets the value of the actuate property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getActuate() {
		return actuate;
	}

	/**
	 * Sets the value of the actuate property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setActuate(String value) {
		actuate = value;
	}

	/**
	 * Gets the value of the language property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLanguage(String value) {
		language = value;
	}

	/**
	 * Gets the value of the lang property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the value of the lang property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLang(String value) {
		lang = value;
	}

	/**
	 * Gets the value of the script property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getScript() {
		return script;
	}

	/**
	 * Sets the value of the script property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setScript(String value) {
		script = value;
	}

	/**
	 * Gets the value of the transliteration property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTransliteration() {
		return transliteration;
	}

	/**
	 * Sets the value of the transliteration property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTransliteration(String value) {
		transliteration = value;
	}

}
