//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for nameTypeAttribute.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="nameTypeAttribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="personal"/>
 *     &lt;enumeration value="corporate"/>
 *     &lt;enumeration value="conference"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "nameTypeAttribute")
@XmlEnum
public enum NameTypeAttribute {

	/** 100, 700. */
	@XmlEnumValue("personal")
	PERSONAL("personal"),

	/**
	 * 110, 710.
	 */
	@XmlEnumValue("corporate")
	CORPORATE("corporate"),

	/** 111, 711. */
	@XmlEnumValue("conference")
	CONFERENCE("conference");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new name type attribute.
	 * 
	 * @param v the v
	 */
	NameTypeAttribute(String v) {
		value = v;
	}

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 * 
	 * @param v the v
	 * @return the name type attribute
	 */
	public static NameTypeAttribute fromValue(String v) {
		for (NameTypeAttribute c : NameTypeAttribute.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
