//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/mods/v3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED/*
																																				 * ,
																																				 * xmlns
																																				 * =
																																				 * {
																																				 * @
																																				 * javax
																																				 * .
																																				 * xml
																																				 * .
																																				 * bind
																																				 * .
																																				 * annotation
																																				 * .
																																				 * XmlNs
																																				 * (
																																				 * prefix
																																				 * =
																																				 * "m"
																																				 * ,
																																				 * namespaceURI
																																				 * =
																																				 * "http://www.loc.gov/mods/v3"
																																				 * )
																																				 * ,
																																				 * @
																																				 * javax
																																				 * .
																																				 * xml
																																				 * .
																																				 * bind
																																				 * .
																																				 * annotation
																																				 * .
																																				 * XmlNs
																																				 * (
																																				 * prefix
																																				 * =
																																				 * "xs"
																																				 * ,
																																				 * namespaceURI
																																				 * =
																																				 * "http://www.w3.org/2001/XMLSchema"
																																				 * )
																																				 * }
																																				 */
)
package it.cineca.util.mods3_3.schema;

