//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for placeAuthority.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="placeAuthority">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="marcgac"/>
 *     &lt;enumeration value="marccountry"/>
 *     &lt;enumeration value="iso3166"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "placeAuthority")
@XmlEnum
public enum PlaceAuthority {

	/** The marcgac. */
	@XmlEnumValue("marcgac")
	MARCGAC("marcgac"),
	/** The marccountry. */
	@XmlEnumValue("marccountry")
	MARCCOUNTRY("marccountry"),
	/** The IS o_3166. */
	@XmlEnumValue("iso3166")
	ISO_3166("iso3166");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new place authority.
	 * 
	 * @param v the v
	 */
	PlaceAuthority(String v) {
		value = v;
	}

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 * 
	 * @param v the v
	 * @return the place authority
	 */
	public static PlaceAuthority fromValue(String v) {
		for (PlaceAuthority c : PlaceAuthority.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
