//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for recordInfoType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="recordContentSource" type="{http://www.loc.gov/mods/v3}stringPlusAuthorityPlusLanguage"/>
 *         &lt;element name="recordCreationDate" type="{http://www.loc.gov/mods/v3}dateType"/>
 *         &lt;element name="recordChangeDate" type="{http://www.loc.gov/mods/v3}dateType"/>
 *         &lt;element name="recordIdentifier">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="languageOfCataloging" type="{http://www.loc.gov/mods/v3}languageType"/>
 *         &lt;element name="recordOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descriptionStandard" type="{http://www.loc.gov/mods/v3}stringPlusAuthority"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.loc.gov/mods/v3}language"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordInfoType", propOrder = { "recordContentSourceOrRecordCreationDateOrRecordChangeDate" })
public class RecordInfoType {

	/** The record content source or record creation date or record change date. */
	@XmlElementRefs({ @XmlElementRef(name = "languageOfCataloging", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "recordOrigin", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "recordCreationDate", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "recordIdentifier", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "recordContentSource", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "recordChangeDate", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
			@XmlElementRef(name = "descriptionStandard", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class) })
	protected List<JAXBElement<?>> recordContentSourceOrRecordCreationDateOrRecordChangeDate;

	/** The language. */
	@XmlAttribute(name = "lang")
	protected String language;

	/** The lang. */
	@XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;

	/** The script. */
	@XmlAttribute
	protected String script;

	/** The transliteration. */
	@XmlAttribute
	protected String transliteration;

	/**
	 * Gets the value of the recordContentSourceOrRecordCreationDateOrRecordChangeDate property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
	 * recordContentSourceOrRecordCreationDateOrRecordChangeDate property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRecordContentSourceOrRecordCreationDateOrRecordChangeDate().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link LanguageType }{@code >}
	 * 
	 * @return the record content source or record creation date or record change date {@link JAXBElement }{@code <}{@link String }{@code >}
	 * {@link JAXBElement }{@code <}{@link DateType }{@code >} {@link JAXBElement }{@code <} {@link RecordInfoType.RecordIdentifier }{@code >}
	 * {@link JAXBElement }{@code <}{@link StringPlusAuthorityPlusLanguage }{@code >} {@link JAXBElement }{@code <}{@link DateType }{@code >}
	 * {@link JAXBElement }{@code <}{@link StringPlusAuthority }{@code >}
	 */
	public List<JAXBElement<?>> getRecordContentSourceOrRecordCreationDateOrRecordChangeDate() {
		if (recordContentSourceOrRecordCreationDateOrRecordChangeDate == null) {
			recordContentSourceOrRecordCreationDateOrRecordChangeDate = new ArrayList<JAXBElement<?>>();
		}
		return recordContentSourceOrRecordCreationDateOrRecordChangeDate;
	}

	/**
	 * Gets the value of the language property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLanguage(String value) {
		language = value;
	}

	/**
	 * Gets the value of the lang property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the value of the lang property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLang(String value) {
		lang = value;
	}

	/**
	 * Gets the value of the script property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getScript() {
		return script;
	}

	/**
	 * Sets the value of the script property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setScript(String value) {
		script = value;
	}

	/**
	 * Gets the value of the transliteration property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTransliteration() {
		return transliteration;
	}

	/**
	 * Sets the value of the transliteration property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTransliteration(String value) {
		transliteration = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class RecordIdentifier {

		/** The value. */
		@XmlValue
		protected String value;

		/** The source. */
		@XmlAttribute
		protected String source;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the source property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getSource() {
			return source;
		}

		/**
		 * Sets the value of the source property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setSource(String value) {
			source = value;
		}

	}

}
