//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for stringPlusAuthority complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stringPlusAuthority">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="authority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stringPlusAuthority", propOrder = { "value" })
@XmlSeeAlso({ StringPlusAuthorityPlusDisplayLabel.class, it.cineca.util.mods3_3.schema.RoleType.RoleTerm.class,
		StringPlusAuthorityPlusType.class, StringPlusAuthorityPlusEdition.class, StringPlusAuthorityPlusLanguage.class })
public class StringPlusAuthority {

	/** The value. */
	@XmlValue
	protected String value;

	/** The authority. */
	@XmlAttribute
	protected String authority;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the authority property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAuthority() {
		return authority;
	}

	/**
	 * Sets the value of the authority property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAuthority(String value) {
		authority = value;
	}

}
