//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.10.27 at 12:34:36 PM CET
//

package it.cineca.util.mods3_3.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for titleInfoType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="titleInfoType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.loc.gov/mods/v3}baseTitleInfoType">
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="abbreviated"/>
 *             &lt;enumeration value="translated"/>
 *             &lt;enumeration value="alternative"/>
 *             &lt;enumeration value="uniform"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "titleInfoType")
public class TitleInfoType extends BaseTitleInfoType {

	/** The title type. */
	@XmlAttribute(name = "type")
	protected String titleType;

	/**
	 * Gets the value of the titleType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTitleType() {
		return titleType;
	}

	/**
	 * Sets the value of the titleType property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTitleType(String value) {
		titleType = value;
	}

}
