//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

package it.cineca.util.didl;

import it.cineca.util.didmodel.DIDBaseType;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for DeclarationsType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclarationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}Item"/>
 *         &lt;element ref="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}Descriptor"/>
 *         &lt;element ref="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}Component"/>
 *         &lt;element ref="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}Annotation"/>
 *         &lt;element ref="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}Anchor"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclarationsType", propOrder = { "itemOrDescriptorOrComponent" })
public class DeclarationsType {

	/** The item or descriptor or component. */
	@XmlElementRefs({ @XmlElementRef(name = "Anchor", namespace = "urn:mpeg:mpeg21:2002:02-DIDMODEL-NS", type = JAXBElement.class),
			@XmlElementRef(name = "Item", namespace = "urn:mpeg:mpeg21:2002:02-DIDMODEL-NS", type = JAXBElement.class),
			@XmlElementRef(name = "Component", namespace = "urn:mpeg:mpeg21:2002:02-DIDMODEL-NS", type = JAXBElement.class),
			@XmlElementRef(name = "Annotation", namespace = "urn:mpeg:mpeg21:2002:02-DIDMODEL-NS", type = JAXBElement.class),
			@XmlElementRef(name = "Descriptor", namespace = "urn:mpeg:mpeg21:2002:02-DIDMODEL-NS", type = JAXBElement.class) })
	protected List<JAXBElement<? extends DIDBaseType>> itemOrDescriptorOrComponent;

	/**
	 * Gets the value of the itemOrDescriptorOrComponent property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the itemOrDescriptorOrComponent
	 * property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getItemOrDescriptorOrComponent().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link it.cineca.util.didl.ComponentType }
	 * 
	 * @return the item or descriptor or component {@code >} {@link JAXBElement }{@code <}{@link it.cineca.util.didl.DescriptorType }{@code >}
	 * {@link JAXBElement }{@code <} {@link it.cineca.util.didl.ItemType }{@code >} {@link JAXBElement }{@code <}
	 * {@link it.cineca.util.didmodel.AnchorType }{@code >} {@link JAXBElement }{@code <}{@link it.cineca.util.didmodel.ItemType }{@code >}
	 * {@link JAXBElement }{@code <} {@link it.cineca.util.didmodel.ComponentType }{@code >} {@link JAXBElement }{@code <}
	 * {@link it.cineca.util.didmodel.AnnotationType } {@code >} {@link JAXBElement }{@code <}{@link it.cineca.util.didmodel.DescriptorType }
	 * {@code >} {@link JAXBElement }{@code <} {@link it.cineca.util.didl.AnchorType }{@code >} {@link JAXBElement }{@code <}
	 * {@link it.cineca.util.didl.AnnotationType }{@code >}
	 */
	public List<JAXBElement<? extends DIDBaseType>> getItemOrDescriptorOrComponent() {
		if (itemOrDescriptorOrComponent == null) {
			itemOrDescriptorOrComponent = new ArrayList<JAXBElement<? extends DIDBaseType>>();
		}
		return itemOrDescriptorOrComponent;
	}

}
