//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

package it.cineca.util.didl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for FragmentType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FragmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg21:2002:02-DIDMODEL-NS}FragmentType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fragmentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FragmentType", propOrder = { "any" })
public class FragmentType extends it.cineca.util.didmodel.FragmentType {

	/** The any. */
	@XmlAnyElement(lax = true)
	protected Object any;

	/** The fragment id. */
	@XmlAttribute
	protected String fragmentId;

	/**
	 * Gets the value of the any property.
	 * 
	 * @return possible object is {@link Object } {@link Element }
	 */
	public Object getAny() {
		return any;
	}

	/**
	 * Sets the value of the any property.
	 * 
	 * @param value allowed object is {@link Object } {@link Element }
	 */
	public void setAny(Object value) {
		any = value;
	}

	/**
	 * Gets the value of the fragmentId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getFragmentId() {
		return fragmentId;
	}

	/**
	 * Sets the value of the fragmentId property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setFragmentId(String value) {
		fragmentId = value;
	}

}
