//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.05.09 at 04:56:30 PM CEST
//

package it.cineca.util.oai.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for deletedRecordType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="deletedRecordType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="no"/>
 *     &lt;enumeration value="persistent"/>
 *     &lt;enumeration value="transient"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlEnum
public enum DeletedRecordType {

	/** The no. */
	@XmlEnumValue("no")
	NO("no"),
	/** The persistent. */
	@XmlEnumValue("persistent")
	PERSISTENT("persistent"),
	/** The transient. */
	@XmlEnumValue("transient")
	TRANSIENT("transient");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new deleted record type.
	 * 
	 * @param v the v
	 */
	DeletedRecordType(String v) {
		value = v;
	}

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 * 
	 * @param v the v
	 * @return the deleted record type
	 */
	public static DeletedRecordType fromValue(String v) {
		for (DeletedRecordType c : DeletedRecordType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
