//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.05.09 at 04:56:30 PM CEST
//

package it.cineca.util.oai.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for granularityType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="granularityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="YYYY-MM-DD"/>
 *     &lt;enumeration value="YYYY-MM-DDThh:mm:ssZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlEnum
public enum GranularityType {

	/** The yyyy mm dd. */
	@XmlEnumValue("YYYY-MM-DD")
	YYYY_MM_DD("YYYY-MM-DD"),
	/** The yyyy mm dd thh mm ss z. */
	@XmlEnumValue("YYYY-MM-DDThh:mm:ssZ")
	YYYY_MM_DD_THH_MM_SS_Z("YYYY-MM-DDThh:mm:ssZ");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new granularity type.
	 * 
	 * @param v the v
	 */
	GranularityType(String v) {
		value = v;
	}

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 * 
	 * @param v the v
	 * @return the granularity type
	 */
	public static GranularityType fromValue(String v) {
		for (GranularityType c : GranularityType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
