//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.05.09 at 04:56:30 PM CEST
//

package it.cineca.util.oai.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for metadataFormatType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataFormatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadataPrefix" type="{http://www.openarchives.org/OAI/2.0/}metadataPrefixType"/>
 *         &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="metadataNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataFormatType", propOrder = { "metadataPrefix", "schema", "metadataNamespace" })
public class MetadataFormatType {

	/** The metadata prefix. */
	@XmlElement(required = true)
	protected String metadataPrefix;

	/** The schema. */
	@XmlElement(required = true)
	protected String schema;

	/** The metadata namespace. */
	@XmlElement(required = true)
	protected String metadataNamespace;

	/**
	 * Gets the value of the metadataPrefix property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMetadataPrefix() {
		return metadataPrefix;
	}

	/**
	 * Sets the value of the metadataPrefix property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setMetadataPrefix(String value) {
		metadataPrefix = value;
	}

	/**
	 * Gets the value of the schema property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSchema() {
		return schema;
	}

	/**
	 * Sets the value of the schema property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSchema(String value) {
		schema = value;
	}

	/**
	 * Gets the value of the metadataNamespace property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMetadataNamespace() {
		return metadataNamespace;
	}

	/**
	 * Sets the value of the metadataNamespace property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setMetadataNamespace(String value) {
		metadataNamespace = value;
	}

}
