//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.05.09 at 04:56:30 PM CEST
//

package it.cineca.util.oai.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for OAI-PMHerrorcodeType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="OAI-PMHerrorcodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="cannotDisseminateFormat"/>
 *     &lt;enumeration value="idDoesNotExist"/>
 *     &lt;enumeration value="badArgument"/>
 *     &lt;enumeration value="badVerb"/>
 *     &lt;enumeration value="noMetadataFormats"/>
 *     &lt;enumeration value="noRecordsMatch"/>
 *     &lt;enumeration value="badResumptionToken"/>
 *     &lt;enumeration value="noSetHierarchy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlEnum
public enum OAIPMHerrorcodeType {

	/** The cannot disseminate format. */
	@XmlEnumValue("cannotDisseminateFormat")
	CANNOT_DISSEMINATE_FORMAT("cannotDisseminateFormat"),
	/** The id does not exist. */
	@XmlEnumValue("idDoesNotExist")
	ID_DOES_NOT_EXIST("idDoesNotExist"),
	/** The bad argument. */
	@XmlEnumValue("badArgument")
	BAD_ARGUMENT("badArgument"),
	/** The bad verb. */
	@XmlEnumValue("badVerb")
	BAD_VERB("badVerb"),
	/** The no metadata formats. */
	@XmlEnumValue("noMetadataFormats")
	NO_METADATA_FORMATS("noMetadataFormats"),
	/** The no records match. */
	@XmlEnumValue("noRecordsMatch")
	NO_RECORDS_MATCH("noRecordsMatch"),
	/** The bad resumption token. */
	@XmlEnumValue("badResumptionToken")
	BAD_RESUMPTION_TOKEN("badResumptionToken"),
	/** The no set hierarchy. */
	@XmlEnumValue("noSetHierarchy")
	NO_SET_HIERARCHY("noSetHierarchy");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new oAIPM herrorcode type.
	 * 
	 * @param v the v
	 */
	OAIPMHerrorcodeType(String v) {
		value = v;
	}

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 * 
	 * @param v the v
	 * @return the oAIPM herrorcode type
	 */
	public static OAIPMHerrorcodeType fromValue(String v) {
		for (OAIPMHerrorcodeType c : OAIPMHerrorcodeType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
