//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.05.09 at 04:56:30 PM CEST
//

package it.cineca.util.oai.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

// TODO: Auto-generated Javadoc
/**
 * Define requestType, indicating the protocol request that led to the response. Element content is BASE-URL, attributes are arguments of
 * protocol request, attribute-values are values of arguments of protocol request
 * <p>
 * Java class for requestType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="from" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="identifier" type="{http://www.openarchives.org/OAI/2.0/}identifierType" />
 *       &lt;attribute name="metadataPrefix" type="{http://www.openarchives.org/OAI/2.0/}metadataPrefixType" />
 *       &lt;attribute name="resumptionToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="set" type="{http://www.openarchives.org/OAI/2.0/}setSpecType" />
 *       &lt;attribute name="until" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType" />
 *       &lt;attribute name="verb" type="{http://www.openarchives.org/OAI/2.0/}verbType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = { "value" })
public class RequestType {

	/** The value. */
	@XmlValue
	protected String value;

	/** The from. */
	@XmlAttribute
	protected String from;

	/** The identifier. */
	@XmlAttribute
	protected String identifier;

	/** The metadata prefix. */
	@XmlAttribute
	protected String metadataPrefix;

	/** The resumption token. */
	@XmlAttribute
	protected String resumptionToken;

	/** The set. */
	@XmlAttribute
	protected String set;

	/** The until. */
	@XmlAttribute
	protected String until;

	/** The verb. */
	@XmlAttribute
	protected VerbType verb;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the from property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getFrom() {
		return from;
	}

	/**
	 * Sets the value of the from property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setFrom(String value) {
		from = value;
	}

	/**
	 * Gets the value of the identifier property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setIdentifier(String value) {
		identifier = value;
	}

	/**
	 * Gets the value of the metadataPrefix property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMetadataPrefix() {
		return metadataPrefix;
	}

	/**
	 * Sets the value of the metadataPrefix property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setMetadataPrefix(String value) {
		metadataPrefix = value;
	}

	/**
	 * Gets the value of the resumptionToken property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getResumptionToken() {
		return resumptionToken;
	}

	/**
	 * Sets the value of the resumptionToken property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setResumptionToken(String value) {
		resumptionToken = value;
	}

	/**
	 * Gets the value of the set property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSet() {
		return set;
	}

	/**
	 * Sets the value of the set property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSet(String value) {
		set = value;
	}

	/**
	 * Gets the value of the until property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getUntil() {
		return until;
	}

	/**
	 * Sets the value of the until property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setUntil(String value) {
		until = value;
	}

	/**
	 * Gets the value of the verb property.
	 * 
	 * @return possible object is {@link VerbType }
	 */
	public VerbType getVerb() {
		return verb;
	}

	/**
	 * Sets the value of the verb property.
	 * 
	 * @param value allowed object is {@link VerbType }
	 */
	public void setVerb(VerbType value) {
		verb = value;
	}

}
