//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

package it.cineca.util.dip;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for MethodInfoType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Argument" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="autoRun" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="profileCompliance" type="{urn:mpeg:mpeg21:2005:01-DIP-NS}ProfileComplianceType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodInfoType", propOrder = { "argument" })
public class MethodInfoType {

	/** The argument. */
	@XmlElement(name = "Argument")
	@XmlSchemaType(name = "anyURI")
	protected List<String> argument;

	/** The auto run. */
	@XmlAttribute
	protected Boolean autoRun;

	/** The profile compliance. */
	@XmlAttribute
	protected List<QName> profileCompliance;

	/**
	 * Gets the value of the argument property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the argument property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArgument().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * @return the argument
	 */
	public List<String> getArgument() {
		if (argument == null) {
			argument = new ArrayList<String>();
		}
		return argument;
	}

	/**
	 * Gets the value of the autoRun property.
	 * 
	 * @return possible object is {@link Boolean }
	 */
	public boolean isAutoRun() {
		if (autoRun == null) {
			return false;
		}
		else {
			return autoRun;
		}
	}

	/**
	 * Sets the value of the autoRun property.
	 * 
	 * @param value allowed object is {@link Boolean }
	 */
	public void setAutoRun(Boolean value) {
		autoRun = value;
	}

	/**
	 * Gets the value of the profileCompliance property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the profileCompliance property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProfileCompliance().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link QName }
	 * 
	 * @return the profile compliance
	 */
	public List<QName> getProfileCompliance() {
		if (profileCompliance == null) {
			profileCompliance = new ArrayList<QName>();
		}
		return profileCompliance;
	}

}
