//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

package it.cineca.util.dip;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the it.cineca.util.dip
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/** The Constant _JDIXOClasses_QNAME. */
	private static final QName _JDIXOClasses_QNAME = new QName("urn:mpeg:mpeg21:2005:01-DIP-NS", "JDIXOClasses");

	/** The Constant _MethodInfo_QNAME. */
	private static final QName _MethodInfo_QNAME = new QName("urn:mpeg:mpeg21:2005:01-DIP-NS", "MethodInfo");

	/** The Constant _ObjectType_QNAME. */
	private static final QName _ObjectType_QNAME = new QName("urn:mpeg:mpeg21:2005:01-DIP-NS", "ObjectType");

	/** The Constant _Label_QNAME. */
	private static final QName _Label_QNAME = new QName("urn:mpeg:mpeg21:2005:01-DIP-NS", "Label");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cineca.util.dip
	 */
	public ObjectFactory() {}

	/**
	 * Create an instance of {@link MethodInfoType }.
	 * 
	 * @return the method info type
	 */
	public MethodInfoType createMethodInfoType() {
		return new MethodInfoType();
	}

	/**
	 * Create an instance of {@link ObjectTypeType }.
	 * 
	 * @return the object type type
	 */
	public ObjectTypeType createObjectTypeType() {
		return new ObjectTypeType();
	}

	/**
	 * Create an instance of {@link LabelType }.
	 * 
	 * @return the label type
	 */
	public LabelType createLabelType() {
		return new LabelType();
	}

	/**
	 * Create an instance of {@link JDIXOClassesType }.
	 * 
	 * @return the JDIXO classes type
	 */
	public JDIXOClassesType createJDIXOClassesType() {
		return new JDIXOClassesType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link JDIXOClassesType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< jdixo classes type>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2005:01-DIP-NS", name = "JDIXOClasses")
	public JAXBElement<JDIXOClassesType> createJDIXOClasses(JDIXOClassesType value) {
		return new JAXBElement<JDIXOClassesType>(_JDIXOClasses_QNAME, JDIXOClassesType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MethodInfoType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< method info type>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2005:01-DIP-NS", name = "MethodInfo")
	public JAXBElement<MethodInfoType> createMethodInfo(MethodInfoType value) {
		return new JAXBElement<MethodInfoType>(_MethodInfo_QNAME, MethodInfoType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ObjectTypeType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< object type type>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2005:01-DIP-NS", name = "ObjectType")
	public JAXBElement<ObjectTypeType> createObjectType(ObjectTypeType value) {
		return new JAXBElement<ObjectTypeType>(_ObjectType_QNAME, ObjectTypeType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link LabelType }{@code >}.
	 * 
	 * @param value the value
	 * @return the JAXB element< label type>
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg21:2005:01-DIP-NS", name = "Label")
	public JAXBElement<LabelType> createLabel(LabelType value) {
		return new JAXBElement<LabelType>(_Label_QNAME, LabelType.class, null, value);
	}

}
