//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.09 at 11:45:08 AM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:mpeg:mpeg21:2005:01-DIP-NS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.cineca.util.dip;

